FROM odinlmshen/autoware-simulator:v1.0

COPY components/simulator/second_sight_scenario_test_runner.launch.py \
    /opt/autoware/share/scenario_test_runner/launch/second_sight_scenario_test_runner.launch.py
